### ISSUE TITLE
No Data for KVB

### ISSUE THREAD

**Issue by mkcologne** [derf/db-fakedisplay#27]
`SSL connect attempt failed error:0A000086:SSL routines::certificate verify failed`

tried over:
https://dbf.finalrewind.org

Reproducable:
Yes - for more that a week now.

Thanks - Michael

**Comment by derf** [comment]
Looks like KVB did not properly set up their TLS certificate.

**Comment by mkcologne** [comment]
Sahel I blame them that I did for decades? 😉

**Comment by derf** [comment]
Workaround deployed in https://github.com/derf/Travel-Status-DE-DeutscheBahn/commit/b9116cbee16a91bec5eb3584431bac22759faef5, will end up on dbf eventually.

**Comment by derf** [comment]
Fixed

**Comment by shred** [comment]
The error is still shown on KVB backend. Has the fix been deployed yet?

**Comment by mkcologne** [comment]
It seemed fixed, but came back.

**Comment by mkcologne** [comment]
Seems it was an KVB Issue.
Not the only one the KVB has. 😉
